# Generated by Django 3.2.9 on 2021-11-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderSubmitted',
            fields=[
                ('orderID', models.IntegerField(default=0)),
                ('userID', models.CharField(max_length=20)),
                ('orderType', models.CharField(max_length=20)),
                ('employeeID', models.CharField(max_length=20)),
                ('dateVisit', models.DateTimeField()),
                ('orderDescription', models.TextField()),
                ('paymentID', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='paymentSubmitted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nextPayment', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('paymentType', models.CharField(max_length=20)),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCore.ordersubmitted')),
            ],
        ),
    ]
