# Generated by Django 3.2.9 on 2021-11-03 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0002_ordersubmitted_paymentsubmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('orderType', models.CharField(max_length=20)),
                ('nextPayment', models.DateTimeField()),
                ('amount', models.IntegerField(default=0)),
                ('employeeID', models.CharField(max_length=20)),
                ('dateVisit', models.DateTimeField()),
                ('orderDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCore.order')),
            ],
        ),
        migrations.CreateModel(
            name='paymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentsubmitted',
            name='paymentID',
        ),
        migrations.DeleteModel(
            name='orderSubmitted',
        ),
        migrations.DeleteModel(
            name='paymentSubmitted',
        ),
        migrations.AddField(
            model_name='payment',
            name='paymentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiCore.paymenttype'),
        ),
    ]
