# Generated by Django 3.2.9 on 2021-11-09 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0003_auto_20211103_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateVisit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nextPayment',
        ),
    ]
