# Generated by Django 3.2.9 on 2021-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0004_auto_20211109_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AddField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
