# Generated by Django 3.2.9 on 2021-11-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0006_auto_20211111_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(default=''),
        ),
    ]
