# Generated by Django 3.2.9 on 2021-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0007_auto_20211111_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(default='1999-01-01'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(default='1999-01-01'),
        ),
    ]
