# Generated by Django 3.2.9 on 2021-11-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0009_auto_20211111_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateVisit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nextPayment',
        ),
    ]
