# Generated by Django 3.2.9 on 2021-11-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0010_auto_20211111_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
