# Generated by Django 3.2.9 on 2021-12-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0011_auto_20211111_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDescription',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderType',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='edited',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='improvement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Especial')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='dateVisit',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='order',
            name='employeeID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='nextPayment',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
