# Generated by Django 3.2.9 on 2021-12-11 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0012_auto_20211211_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('professionalAssigned', models.IntegerField()),
                ('question1', models.CharField(blank=True, max_length=100)),
                ('answer1', models.CharField(blank=True, max_length=100)),
                ('question2', models.CharField(blank=True, max_length=100)),
                ('answer2', models.CharField(blank=True, max_length=100)),
                ('question3', models.CharField(blank=True, max_length=100)),
                ('answer3', models.CharField(blank=True, max_length=100)),
                ('question4', models.CharField(blank=True, max_length=100)),
                ('answer4', models.CharField(blank=True, max_length=100)),
                ('question5', models.CharField(blank=True, max_length=100)),
                ('answer5', models.CharField(blank=True, max_length=100)),
                ('orderID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extend', to='apiCore.order')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('professionalAssigned', models.IntegerField()),
                ('client1', models.IntegerField()),
                ('client2', models.IntegerField()),
                ('client3', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='messageModel',
        ),
        migrations.DeleteModel(
            name='payment',
        ),
        migrations.DeleteModel(
            name='paymentType',
        ),
    ]
