# Generated by Django 3.2.9 on 2021-12-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0013_auto_20211211_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userID',
            new_name='IDuser',
        ),
    ]
