# Generated by Django 3.2.9 on 2021-12-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiCore', '0014_rename_userid_order_iduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='IDuser',
            new_name='userID',
        ),
    ]
